import csv
import math
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Put your raw trial files here (generated by step6_collect.sh)
RAW_DIR = "raw_trials"
OUT_SUMMARY = "summary.csv"

POLICIES = ["round_robin", "least_loaded", "ml_pred"]

def percentile(xs, p):
    xs = np.sort(xs)
    k = int(round((p/100.0) * (len(xs)-1)))
    return float(xs[k])

def mean_ci95(xs):
    xs = np.array(xs, dtype=float)
    n = len(xs)
    mu = float(xs.mean())
    if n < 2:
        return mu, 0.0
    s = float(xs.std(ddof=1))
    # normal approx CI (fine for n>=30); for small n use t-dist if desired
    half = 1.96 * (s / math.sqrt(n))
    return mu, half

def load_policy_trials(policy):
    # expects files: raw_trials/<policy>_trial*.csv
    files = sorted([f for f in os.listdir(RAW_DIR) if f.startswith(policy) and f.endswith(".csv")])
    all_lat = []
    per_trial = []
    for f in files:
        df = pd.read_csv(os.path.join(RAW_DIR, f))
        lat = df["latency_sec"].values.tolist()
        per_trial.append(lat)
        all_lat.extend(lat)
    return files, per_trial, all_lat

def plot_boxplot(data_by_policy):
    plt.figure()
    labels = list(data_by_policy.keys())
    data = [data_by_policy[k] for k in labels]
    plt.boxplot(data, labels=labels, showfliers=False)
    plt.ylabel("Latency (sec)")
    plt.title("HTTP Latency Distribution (Boxplot)")
    plt.tight_layout()
    plt.savefig("latency_boxplot.png", dpi=200)

def plot_cdf(data_by_policy):
    plt.figure()
    for policy, xs in data_by_policy.items():
        xs = np.sort(np.array(xs, dtype=float))
        ys = np.arange(1, len(xs)+1) / len(xs)
        plt.plot(xs, ys, label=policy)
    plt.xlabel("Latency (sec)")
    plt.ylabel("CDF")
    plt.title("HTTP Latency CDF")
    plt.legend()
    plt.tight_layout()
    plt.savefig("latency_cdf.png", dpi=200)

def main():
    os.makedirs(RAW_DIR, exist_ok=True)

    summary_rows = []
    data_by_policy = {}

    for policy in POLICIES:
        files, per_trial, all_lat = load_policy_trials(policy)
        if len(all_lat) == 0:
            print(f"[WARN] No data found for {policy} in {RAW_DIR}/")
            continue

        mu, ci = mean_ci95(all_lat)
        p50 = percentile(all_lat, 50)
        p95 = percentile(all_lat, 95)
        std = float(np.std(all_lat, ddof=1)) if len(all_lat) > 1 else 0.0

        summary_rows.append({
            "policy": policy,
            "num_trials": len(files),
            "num_samples": len(all_lat),
            "mean_latency_sec": mu,
            "ci95_halfwidth_sec": ci,
            "p50_sec": p50,
            "p95_sec": p95,
            "std_sec": std
        })

        data_by_policy[policy] = all_lat



    if not summary_rows:
     print(f"[ERROR] No trial CSV files found in {RAW_DIR}/.")
     print("Expected files like: raw_trials/round_robin_trial1.csv")
     return

    df = pd.DataFrame(summary_rows).sort_values("policy")
    df.to_csv(OUT_SUMMARY, index=False)
    print("Wrote:", OUT_SUMMARY)
    print(df)

    if data_by_policy:
        plot_boxplot(data_by_policy)
        plot_cdf(data_by_policy)
        print("Wrote: latency_boxplot.png, latency_cdf.png")

if __name__ == "__main__":
    main()